Prénom - User Storie #4
AnthoLFB/AnthonyLefebvre_12_23052022 pull request #18
Opened 2022-06-07 18:29 UTC by AnthoLFB

**Problématique :**

En tant qu’utilisateur, je veux que mon prénom soit affiché sur le dashboard (le prénom étant récupérée via les données de l’API via la route /user/:id).

**Fonctionnalités :**

- Création des données mockées
- Récupération des données
- Création du composant UserIdentity
- Utilisation des données asynchrones
- Import du composant sur les pages

2022-06-08 09:19 UTC, TBoileau requested changes

2022-06-08 09:19 UTC, TBoileau commented on src/repositories/repository_factory.js
> +}
L'idée c'est plutot de simplement renvoyer l'instance du repository qui te convient.
https://gist.github.com/TBoileau/c9d542325cd9f2900ac0ea5372edf662

2022-06-09 15:03 UTC, AnthoLFB commented on src/repositories/repository_factory.js
> +}
Je vois, j'ai modifié la structure du coup (je me suis inspiré de ce que tu m'a montré dans le lien). Si tu peux me donner ton avis. Merci.

2022-06-13 07:52 UTC, TBoileau approved these changes

2022-06-16 14:17 UTC, merged